#!/usr/bin/env node
// Regenerates font-independent rune outlines + the subsetted web font from a pinned
// Noto Sans Runic release (OFL-1.1). Output is committed; CI does not need to run this.
//
//   node packages/core/scripts/build-glyphs.mjs
//
// Needs: curl, unzip, pyftsubset (pip install fonttools brotli).
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { encode } from "@toon-format/toon";
import opentype from "opentype.js";

const RELEASE = "NotoSansRunic-v2.002";
const URL = `https://github.com/notofonts/runic/releases/download/${RELEASE}/${RELEASE}.zip`;
const TTF = "NotoSansRunic/unhinted/ttf/NotoSansRunic-Regular.ttf";
const TTF_SHA256 = "3510a352a373b87ebc4564109903a833d9f8239251601189f5f0719b9b389acf";
const FIRST = 0x16a0;
const LAST = 0x16f8;

const here = dirname(fileURLToPath(import.meta.url));
const core = join(here, "..");
const web = join(core, "..", "web");
const work = mkdtempSync(join(tmpdir(), "runic-font-"));

execFileSync("curl", ["-fsSL", URL, "-o", join(work, "font.zip")]);
execFileSync("unzip", ["-q", "-o", join(work, "font.zip"), "-d", work]);
const ttfPath = join(work, TTF);
const ttf = readFileSync(ttfPath);
const sha = createHash("sha256").update(ttf).digest("hex");
if (sha !== TTF_SHA256) throw new Error(`Font hash mismatch: ${sha}`);

const font = opentype.parse(ttf.buffer.slice(ttf.byteOffset, ttf.byteOffset + ttf.byteLength));
const upm = font.unitsPerEm;
const ascender = font.ascender;
const descender = font.descender;
const round = (n) => Math.round(n * 10) / 10;

const glyphs = [];
const missing = [];
for (let cp = FIRST; cp <= LAST; cp++) {
  const g = font.charToGlyph(String.fromCodePoint(cp));
  if (!g || g.index === 0) {
    missing.push(cp);
    continue;
  }
  // opentype.js getPath uses y-down screen space at baseline y = ascender
  const path = g.getPath(0, ascender, upm).toPathData({ decimalPlaces: 1, flipY: false });
  glyphs.push({
    cp: `U+${cp.toString(16).toUpperCase()}`,
    glyph: String.fromCodePoint(cp),
    advance: round(g.advanceWidth ?? upm),
    d: path,
  });
}
if (missing.length) throw new Error(`Font lacks: ${missing.map((c) => c.toString(16)).join(", ")}`);

const doc = {
  meta: {
    name: "runic-glyph-outlines",
    source: `${RELEASE} ${TTF}`,
    sha256: TTF_SHA256,
    license: "OFL-1.1 (derived from Noto Sans Runic; see OFL.txt)",
    unitsPerEm: upm,
    ascender,
    descender,
    coords: "SVG, y down, baseline at y=ascender, viewBox 0 0 advance (ascender - descender)",
  },
  glyphs,
};
const header = [
  "# Rune outlines so runes render without any installed font.",
  "# Generated by packages/core/scripts/build-glyphs.mjs. Do not edit by hand.",
  "",
].join("\n");
writeFileSync(join(core, "data", "runic-glyphs.toon"), `${header}${encode(doc, { delimiter: "|" })}\n`);
copyFileSync(join(work, "OFL.txt"), join(core, "data", "OFL-NotoSansRunic.txt"));

mkdirSync(join(web, "public", "fonts"), { recursive: true });
execFileSync("pyftsubset", [
  ttfPath,
  `--unicodes=U+0020,U+16A0-16F8`,
  "--flavor=woff2",
  "--layout-features=*",
  `--output-file=${join(web, "src", "assets", "NotoSansRunic-subset.woff2")}`,
]);
copyFileSync(join(work, "OFL.txt"), join(web, "public", "fonts", "OFL-NotoSansRunic.txt"));

console.log(`glyphs: ${glyphs.length}, upm ${upm}`);
