#!/usr/bin/env node
// Embeds data/*.toon into a TS module so core stays filesystem-free (browser, Node, workers).
//   node packages/core/scripts/embed-data.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const core = join(dirname(fileURLToPath(import.meta.url)), "..");
export const FILES = { lexicon: "runic-lexicon.toon", glyphs: "runic-glyphs.toon" };

export function render() {
  const parts = ["// Generated by scripts/embed-data.mjs from data/*.toon. Do not edit.", ""];
  for (const [name, file] of Object.entries(FILES)) {
    const text = readFileSync(join(core, "data", file), "utf8");
    parts.push(`export const ${name}Toon: string = ${JSON.stringify(text)};`, "");
  }
  return parts.join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(join(core, "src", "runes", "data.generated.ts"), render());
  console.log("wrote src/runes/data.generated.ts");
}
